worker:
    #container_name: service_worker
    build: .
    environment:
        - MQ_HOST=3.83.208.153
        - MQ_USERNAME=worker
        - MQ_PASSWORD=worker
        - MQ_WORKER_QUEUE_NAME=worker_queue
        - MQ_ANALYZER_QUEUE_NAME=analyzer_queue
        - VIDEO_PATH=/tmp
    volumes:
        - /tmp:/tmp
        
        